export { default as API } from "./api";
export { default as examApi } from "./exam";
export { default as certificateApi } from "./certificate";
export { default as classApi } from "./class";
export { default as studentConsultationApi } from "./studentConsultation";
export * from "./utils";
export * from "./user";
export * from "./auth";
export * from "./course";
export * from "./certificate";
export * from "./class";
export * from "./shift";
export * from "./image";
